#https://docs.travis-ci.com/user/languages/c/#Default-Test-Script
#.travis.yml
language: C
script: make
compiler:
  - clang
  - gcc

before_install:
- |
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
  cd SDL2-2.0.8
  ./configure
  make
  sudo make install

addons:
  apt:
    packages:
    - libsdl2-image-2.0-0
    - libsdl2-image-dev
    - libsdl2-mixer-2.0-0
    - libsdl2-mixer-dev
    - libsdl2-ttf-2.0-0
    - libsdl2-ttf-dev
